### PR TITLE
Allow missing coverage via an environment variable

### PR DESCRIPTION
**Pull request by vitaliytv**

### CODE REVIEW

**Comment by jaydenseric** [comment]
Thanks for the contribution; I've got a lot going on at the moment but I hope to process this PR within the next few days.

**Review by jaydenseric — CHANGES_REQUESTED** [review]
Sorry for not getting back to this sooner!

Firstly, we need to rebase this PR on the changes in `master` branch.

The `IGNORE_COVERAGE` environment variable name needs some consideration. "Ignoring" in regards to this package refers to ignoring regions of coverage that may or may not be uncovered, via ignore comments; it shows up as yellow/orange in the CLI report after tests pass. Someone that reads `IGNORE_COVERAGE` might expect that it does what ignore comments do, and might assume that it would maybe make all files yellow/ignored. In fact, it doesn't ignore any of the files. The full coverage report happens as usual, all this environment variable does is prevent missing coverage from causing an error exit code.

Long name, but just an example of clearer semantics: `TOLERATE_INCOMPLETE_COVERAGE`.

Ideally, we could find examples of similar environment variable names to perhaps align with existing ones. I tried searching around the docs for popular testing frameworks for 10 minutes and strangely couldn't find any, but surely they exist!

We also need to add tests.

**Comment by vitaliytv** [comment]
> we need to rebase

we need to rebase - done
rename ENV - done
need to add tests - can you help me with this ?

**Review by jaydenseric — APPROVED** [review]
Thanks for getting the ball rolling, and for your patience!

**Comment by jaydenseric** [comment]
Published in [v6.1.0](https://github.com/jaydenseric/coverage-node/releases/tag/v6.1.0) 🚀

**Pull request merged**
